modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]] #mandatory
modId="void_tome" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Void Tome" #mandatory
credits="pls lyof make me a mod on lcc pretty please?" #optional
authors="nikgub_" #optional
description='''
'''
[[dependencies.examplemod]] #optional
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
